### PR TITLE
improve font-weight and font-style detecting

### PR DESCRIPTION
**Pull request by aalexeev239**
font-weight property is detected in accordance with https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping
font-weight must be prefixed with `-` to avoid interpolations with font name

### CODE REVIEW

**Comment by sapegin** [comment]
Hey @aalexeev239, I’d like to merge this PR if you update the tests too. (And sorry for the delay :–)

**Comment by aalexeev239** [comment]
Hey @sapegin,  I'll look on it and update in few days.

**Comment by sapegin** [comment]
Cool!

**Comment by aalexeev239** [comment]
Hey @sapegin 
Found out that you have incorrect test expectations
https://monosnap.com/file/dgtS1HMhgrzNANiStLaRYTzmAAbGvl
**Bold** font weight must map to `font-weight: 700;`

**Comment by sapegin** [comment]
Could you change that too?

**Comment by aalexeev239** [comment]
Hi, @sapegin!
@c01nd01r improved this PR.

```
Привет!
Я обновил твой форк до актуальной версии и добавил тесты для твоего PR, который лежит в sapegin/fontoptim.
```

P.S. думаю, можно уйти от языкового барьера.

**Comment by sapegin** [comment]
Please use English when posting to this project.

**Pull request closed without merging**
